using System;
using System.Collections.Generic;
using System.Text;

namespace RpcWatsonTcp.SourceGenerator
{
    /// <summary>
    /// Turns a <see cref="ProtoFile"/> model into a C# source string.
    /// </summary>
    internal static class CSharpEmitter
    {
        // Proto3 scalar type → (C# type, default value)
        private static readonly Dictionary<string, (string CsType, string Default)> ScalarMap =
            new Dictionary<string, (string, string)>
            {
                { "string",  ("string",  "string.Empty") },
                { "int32",   ("int",     "0") },
                { "int64",   ("long",    "0") },
                { "uint32",  ("uint",    "0") },
                { "uint64",  ("ulong",   "0") },
                { "sint32",  ("int",     "0") },
                { "sint64",  ("long",    "0") },
                { "fixed32", ("uint",    "0") },
                { "fixed64", ("ulong",   "0") },
                { "sfixed32",("int",     "0") },
                { "sfixed64",("long",    "0") },
                { "float",   ("float",   "0f") },
                { "double",  ("double",  "0.0") },
                { "bool",    ("bool",    "false") },
                { "bytes",   ("byte[]",  "System.Array.Empty<byte>()") },
            };

        /// <summary>
        /// Emit a complete C# file for the given <paramref name="file"/>.
        /// </summary>
        /// <param name="file">Parsed proto model.</param>
        /// <param name="namespaceName">C# namespace for generated types.</param>
        public static string Emit(ProtoFile file, string namespaceName)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using PolyType;");
            sb.AppendLine("using RpcWatsonTcp;");
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");

            foreach (var msg in file.Messages)
                EmitMessage(sb, msg, indent: 1);

            foreach (var enumDef in file.Enums)
                EmitEnum(sb, enumDef, indent: 1);

            sb.AppendLine("}");
            return sb.ToString();
        }

        // ── Message ──────────────────────────────────────────────────────────

        private static void EmitMessage(StringBuilder sb, ProtoMessage msg, int indent)
        {
            string ind = Indent(indent);
            string rpcInterface = GetRpcInterface(msg.Name);
            string baseClause = rpcInterface.Length > 0 ? $" : {rpcInterface}" : string.Empty;

            sb.AppendLine($"{ind}[GenerateShape]");
            sb.AppendLine($"{ind}public partial class {msg.Name}{baseClause}");
            sb.AppendLine($"{ind}{{");

            // Nested enums first
            foreach (var nested in msg.NestedEnums)
                EmitEnum(sb, nested, indent + 1);

            // Nested messages
            foreach (var nested in msg.NestedMessages)
                EmitMessage(sb, nested, indent + 1);

            // Fields
            foreach (var field in msg.Fields)
                EmitField(sb, field, indent + 1);

            sb.AppendLine($"{ind}}}");
            sb.AppendLine();
        }

        private static void EmitField(StringBuilder sb, ProtoField field, int indent)
        {
            string ind = Indent(indent);
            string propName = SnakeToPascal(field.Name);
            var resolved = ResolveType(field.TypeName, field.Repeated);
            sb.AppendLine(ind + "public " + resolved.Item1 + " " + propName + " { get; set; } = " + resolved.Item2 + ";");
        }

        // ── Enum ─────────────────────────────────────────────────────────────

        private static void EmitEnum(StringBuilder sb, ProtoEnum enumDef, int indent)
        {
            string ind = Indent(indent);
            sb.AppendLine($"{ind}public enum {enumDef.Name}");
            sb.AppendLine($"{ind}{{");
            foreach (var val in enumDef.Values)
                sb.AppendLine($"{Indent(indent + 1)}{ScreamingToPascal(val.Name)} = {val.Number},");
            sb.AppendLine($"{ind}}}");
            sb.AppendLine();
        }

        // ── Helpers ──────────────────────────────────────────────────────────

        private static string GetRpcInterface(string messageName)
        {
            if (messageName.EndsWith("Request", StringComparison.Ordinal))
                return "IRequest";
            if (messageName.EndsWith("Reply", StringComparison.Ordinal) ||
                messageName.EndsWith("Response", StringComparison.Ordinal))
                return "IReply";
            return string.Empty;
        }

        private static (string csType, string defaultValue) ResolveType(string protoType, bool repeated)
        {
            if (ScalarMap.TryGetValue(protoType, out var scalar))
            {
                if (repeated)
                    return ("List<" + scalar.CsType + ">", "new List<" + scalar.CsType + ">()");
                return scalar;
            }

            // Enum or message type (user-defined)
            string csName = SimpleName(protoType); // drop package prefix
            if (repeated)
                return ("List<" + csName + ">", "new List<" + csName + ">()");

            // Message types are nullable reference types with a null-forgiving initialiser
            // so the consumer can easily work with them without null-checks in happy-path code.
            return (csName + "?", "null!");
        }

        /// <summary>Strips any package prefix (e.g. "users.Address" → "Address").</summary>
        private static string SimpleName(string typeName)
        {
            int dot = typeName.LastIndexOf('.');
            return dot >= 0 ? typeName.Substring(dot + 1) : typeName;
        }

        /// <summary>Converts proto snake_case to PascalCase: "user_id" → "UserId".</summary>
        internal static string SnakeToPascal(string name)
        {
            var sb = new StringBuilder(name.Length);
            bool upper = true;
            foreach (char c in name)
            {
                if (c == '_') { upper = true; continue; }
                sb.Append(upper ? char.ToUpperInvariant(c) : c);
                upper = false;
            }
            return sb.ToString();
        }

        /// <summary>Converts SCREAMING_SNAKE enum values to PascalCase: "ACTIVE_USER" → "ActiveUser".</summary>
        internal static string ScreamingToPascal(string name)
        {
            var sb = new StringBuilder(name.Length);
            bool upper = true;
            foreach (char c in name)
            {
                if (c == '_') { upper = true; continue; }
                sb.Append(upper ? char.ToUpperInvariant(c) : char.ToLowerInvariant(c));
                upper = false;
            }
            return sb.ToString();
        }

        private static string Indent(int level) => new string(' ', level * 4);
    }
}
