using System;
using System.Text;

namespace RpcWatsonTcp.SourceGenerator
{
    /// <summary>
    /// Orchestrates <see cref="OpenApiEmitter"/>, <see cref="YamlEmitter"/>, and
    /// <see cref="WsdlEmitter"/> and wraps their output in a generated C# file containing
    /// a static partial class with three string properties: OpenApiJson, OpenApiYaml, Wsdl.
    /// </summary>
    internal static class SpecsEmitter
    {
        /// <summary>
        /// Emit a C# file with a <c>{className}Specs</c> static class.
        /// </summary>
        /// <param name="file">Parsed proto model.</param>
        /// <param name="className">Prefix for the generated class name (typically the proto file name without extension).</param>
        /// <param name="namespaceName">C# namespace for the generated class.</param>
        public static string Emit(ProtoFile file, string className, string namespaceName)
        {
            string json  = OpenApiEmitter.Emit(file, className);
            string yaml  = YamlEmitter.Emit(file, className);
            string wsdl  = WsdlEmitter.Emit(file, className);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("namespace " + namespaceName);
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Build-time API specification strings for cross-language client generation.");
            sb.AppendLine("    /// Write to disk with File.WriteAllText(\"openapi.json\", " + className + "Specs.OpenApiJson).");
            sb.AppendLine("    /// </summary>");
            sb.Append("    public static partial class "); sb.Append(className); sb.AppendLine("Specs");
            sb.AppendLine("    {");

            AppendSpecProperty(sb, "OpenApiJson", "OpenAPI 3.0 JSON specification.", json);
            AppendSpecProperty(sb, "OpenApiYaml", "OpenAPI 3.0 YAML specification.", yaml);
            AppendSpecProperty(sb, "Wsdl", "WSDL 1.1 XML specification for SOAP clients.", wsdl);

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void AppendSpecProperty(StringBuilder sb, string propName, string docSummary, string content)
        {
            sb.AppendLine("        /// <summary>" + docSummary + "</summary>");
            sb.Append("        public static string "); sb.Append(propName); sb.Append(" => @\"");
            // Verbatim string literal: escape any embedded double-quotes by doubling them.
            sb.Append(content.Replace("\"", "\"\""));
            sb.AppendLine("\";");
            sb.AppendLine();
        }
    }
}
